name: .NET Core Coverage Report

on:
  push:
    branches:
      - master

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          dotnet-quality: 'ga'

      - name: Install Dependencies and Build
        run: |
          dotnet restore
          dotnet build --no-restore

      - name: Run Tests and Collect Coverage
        run: |
          dotnet test --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
          # Assumes your test projects are set up to output Cobertura format coverage reports.

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: '**/cobertura.xml'
          targetdir: coveragereport
