name: Code Coverage

on:
  push:
    branches: master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        .NET: [8.0, latest]  # Adjust .NET versions as needed

    steps:
      - uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.NET }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: dotnet test tests/MyProject.Tests/**/*.cs --no-build --collect="XPlat Code Coverage" -v diag -- **/bin/Release/netcoreapp**.*.dll

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Replace with your Codecov token
          files: ./coverage/*.xml  # Adjust path if needed
          flags: ${{ matrix.NET }}  # Include .NET version in coverage report

      - name: Calculate code coverage summary (optional)
        run: dotnet report coverage -summary
