name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
          dotnet-quality: 'ga'

      - name: Build and test
        run: |
          dotnet restore
          dotnet build
          dotnet test --collect:"XPlat Code Coverage"

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
        with:
          reports: cobertura.xml
          targetdir: coveragereport

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coveragereport
