name: Build and deploy .NET Core application to Web App STINWeather
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: STINWeather
  AZURE_WEBAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: .
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'
    
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
      with:
        reports: cobertura.xml
        targetdir: coveragereport
